import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { VideoFramesProvider } from "../features/video/context/VideoFramesContext";

const inter = Inter({
  variable: "--font1",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <VideoFramesProvider>{children}</VideoFramesProvider>
      </body>
    </html>
  );
}
